import type { ExerciseDef } from '../types'

// The exercise library. 250 common gym exercises across free weights,
// machines, cables and bodyweight work, organised by muscle/category.
//
// Each exercise is tagged with the muscle group(s) it primarily trains.
// For exercises that clearly target one muscle this is exact (e.g. Barbell
// Curl -> biceps). For broader lifts (rows, deadlifts, cleans, conditioning
// moves) the tagging is a reasonable approximation rather than an exact
// biomechanical breakdown — it only needs to be good enough to colour the
// muscle map on the dashboard, not to replace a kinesiology textbook.
//
// A few names repeat across categories in the source list (e.g. "Cable
// Kickback" appears for both triceps and glutes) — those keep their
// qualifier, e.g. "Cable Kickback (Glutes)", so every name is unique.
export const exerciseLibrary: ExerciseDef[] = [
  { id: 'barbell-bench-press', name: "Barbell Bench Press", category: 'Chest', muscles: ['chest'] },
  { id: 'incline-barbell-bench-press', name: "Incline Barbell Bench Press", category: 'Chest', muscles: ['chest'] },
  { id: 'decline-barbell-bench-press', name: "Decline Barbell Bench Press", category: 'Chest', muscles: ['chest'] },
  { id: 'dumbbell-bench-press', name: "Dumbbell Bench Press", category: 'Chest', muscles: ['chest'] },
  { id: 'incline-dumbbell-bench-press', name: "Incline Dumbbell Bench Press", category: 'Chest', muscles: ['chest'] },
  { id: 'decline-dumbbell-bench-press', name: "Decline Dumbbell Bench Press", category: 'Chest', muscles: ['chest'] },
  { id: 'dumbbell-floor-press', name: "Dumbbell Floor Press", category: 'Chest', muscles: ['chest'] },
  { id: 'close-grip-bench-press', name: "Close-Grip Bench Press", category: 'Chest', muscles: ['chest'] },
  { id: 'machine-chest-press', name: "Machine Chest Press", category: 'Chest', muscles: ['chest'] },
  { id: 'incline-machine-chest-press', name: "Incline Machine Chest Press", category: 'Chest', muscles: ['chest'] },
  { id: 'smith-machine-bench-press', name: "Smith Machine Bench Press", category: 'Chest', muscles: ['chest'] },
  { id: 'smith-machine-incline-press', name: "Smith Machine Incline Press", category: 'Chest', muscles: ['chest'] },
  { id: 'cable-chest-press', name: "Cable Chest Press", category: 'Chest', muscles: ['chest'] },
  { id: 'cable-crossover', name: "Cable Crossover", category: 'Chest', muscles: ['chest'] },
  { id: 'high-to-low-cable-fly', name: "High-to-Low Cable Fly", category: 'Chest', muscles: ['chest'] },
  { id: 'low-to-high-cable-fly', name: "Low-to-High Cable Fly", category: 'Chest', muscles: ['chest'] },
  { id: 'dumbbell-chest-fly', name: "Dumbbell Chest Fly", category: 'Chest', muscles: ['chest'] },
  { id: 'incline-dumbbell-fly', name: "Incline Dumbbell Fly", category: 'Chest', muscles: ['chest'] },
  { id: 'pec-deck-fly', name: "Pec Deck Fly", category: 'Chest', muscles: ['chest'] },
  { id: 'push-ups', name: "Push-Ups", category: 'Chest', muscles: ['chest'] },
  { id: 'wide-grip-push-ups', name: "Wide-Grip Push-Ups", category: 'Chest', muscles: ['chest'] },
  { id: 'diamond-push-ups', name: "Diamond Push-Ups", category: 'Chest', muscles: ['chest'] },
  { id: 'decline-push-ups', name: "Decline Push-Ups", category: 'Chest', muscles: ['chest'] },
  { id: 'incline-push-ups', name: "Incline Push-Ups", category: 'Chest', muscles: ['chest'] },
  { id: 'weighted-push-ups', name: "Weighted Push-Ups", category: 'Chest', muscles: ['chest'] },
  { id: 'pull-ups', name: "Pull-Ups", category: 'Back', muscles: ['lats'] },
  { id: 'chin-ups', name: "Chin-Ups", category: 'Back', muscles: ['lats'] },
  { id: 'neutral-grip-pull-ups', name: "Neutral-Grip Pull-Ups", category: 'Back', muscles: ['lats'] },
  { id: 'lat-pulldown', name: "Lat Pulldown", category: 'Back', muscles: ['lats'] },
  { id: 'close-grip-lat-pulldown', name: "Close-Grip Lat Pulldown", category: 'Back', muscles: ['lats'] },
  { id: 'wide-grip-lat-pulldown', name: "Wide-Grip Lat Pulldown", category: 'Back', muscles: ['lats'] },
  { id: 'neutral-grip-lat-pulldown', name: "Neutral-Grip Lat Pulldown", category: 'Back', muscles: ['lats'] },
  { id: 'single-arm-lat-pulldown', name: "Single-Arm Lat Pulldown", category: 'Back', muscles: ['lats'] },
  { id: 'assisted-pull-up', name: "Assisted Pull-Up", category: 'Back', muscles: ['lats'] },
  { id: 'barbell-bent-over-row', name: "Barbell Bent-Over Row", category: 'Back', muscles: ['upperBack', 'lats'] },
  { id: 'pendlay-row', name: "Pendlay Row", category: 'Back', muscles: ['upperBack', 'lats'] },
  { id: 'yates-row', name: "Yates Row", category: 'Back', muscles: ['upperBack', 'lats'] },
  { id: 'dumbbell-row', name: "Dumbbell Row", category: 'Back', muscles: ['upperBack', 'lats'] },
  { id: 'single-arm-dumbbell-row', name: "Single-Arm Dumbbell Row", category: 'Back', muscles: ['upperBack', 'lats'] },
  { id: 'chest-supported-dumbbell-row', name: "Chest-Supported Dumbbell Row", category: 'Back', muscles: ['upperBack', 'lats'] },
  { id: 't-bar-row', name: "T-Bar Row", category: 'Back', muscles: ['upperBack', 'lats'] },
  { id: 'landmine-row', name: "Landmine Row", category: 'Back', muscles: ['upperBack', 'lats'] },
  { id: 'seated-cable-row', name: "Seated Cable Row", category: 'Back', muscles: ['upperBack', 'lats'] },
  { id: 'close-grip-cable-row', name: "Close-Grip Cable Row", category: 'Back', muscles: ['upperBack', 'lats'] },
  { id: 'wide-grip-cable-row', name: "Wide-Grip Cable Row", category: 'Back', muscles: ['upperBack', 'lats'] },
  { id: 'single-arm-cable-row', name: "Single-Arm Cable Row", category: 'Back', muscles: ['upperBack', 'lats'] },
  { id: 'machine-row', name: "Machine Row", category: 'Back', muscles: ['upperBack', 'lats'] },
  { id: 'chest-supported-machine-row', name: "Chest-Supported Machine Row", category: 'Back', muscles: ['upperBack', 'lats'] },
  { id: 'inverted-row', name: "Inverted Row", category: 'Back', muscles: ['upperBack', 'lats'] },
  { id: 'seal-row', name: "Seal Row", category: 'Back', muscles: ['upperBack', 'lats'] },
  { id: 'meadows-row', name: "Meadows Row", category: 'Back', muscles: ['upperBack', 'lats'] },
  { id: 'barbell-shrug', name: "Barbell Shrug", category: 'Back', muscles: ['upperBack'] },
  { id: 'dumbbell-shrug', name: "Dumbbell Shrug", category: 'Back', muscles: ['upperBack'] },
  { id: 'machine-shrug', name: "Machine Shrug", category: 'Back', muscles: ['upperBack'] },
  { id: 'cable-shrug', name: "Cable Shrug", category: 'Back', muscles: ['upperBack'] },
  { id: 'face-pull', name: "Face Pull", category: 'Back', muscles: ['rearDelts', 'upperBack'] },
  { id: 'straight-arm-pulldown', name: "Straight-Arm Pulldown", category: 'Back', muscles: ['lats'] },
  { id: 'dumbbell-pullover', name: "Dumbbell Pullover", category: 'Back', muscles: ['lats'] },
  { id: 'cable-pullover', name: "Cable Pullover", category: 'Back', muscles: ['lats'] },
  { id: 'back-extension', name: "Back Extension", category: 'Back', muscles: ['lowerBack'] },
  { id: 'barbell-overhead-press', name: "Barbell Overhead Press", category: 'Shoulders', muscles: ['frontDelts', 'sideDelts'] },
  { id: 'dumbbell-shoulder-press', name: "Dumbbell Shoulder Press", category: 'Shoulders', muscles: ['frontDelts', 'sideDelts'] },
  { id: 'seated-dumbbell-shoulder-press', name: "Seated Dumbbell Shoulder Press", category: 'Shoulders', muscles: ['frontDelts', 'sideDelts'] },
  { id: 'arnold-press', name: "Arnold Press", category: 'Shoulders', muscles: ['frontDelts', 'sideDelts'] },
  { id: 'machine-shoulder-press', name: "Machine Shoulder Press", category: 'Shoulders', muscles: ['frontDelts', 'sideDelts'] },
  { id: 'smith-machine-shoulder-press', name: "Smith Machine Shoulder Press", category: 'Shoulders', muscles: ['frontDelts', 'sideDelts'] },
  { id: 'single-arm-dumbbell-press', name: "Single-Arm Dumbbell Press", category: 'Shoulders', muscles: ['frontDelts', 'sideDelts'] },
  { id: 'landmine-press', name: "Landmine Press", category: 'Shoulders', muscles: ['frontDelts', 'sideDelts'] },
  { id: 'single-arm-landmine-press', name: "Single-Arm Landmine Press", category: 'Shoulders', muscles: ['frontDelts', 'sideDelts'] },
  { id: 'cable-shoulder-press', name: "Cable Shoulder Press", category: 'Shoulders', muscles: ['frontDelts', 'sideDelts'] },
  { id: 'dumbbell-lateral-raise', name: "Dumbbell Lateral Raise", category: 'Shoulders', muscles: ['sideDelts'] },
  { id: 'cable-lateral-raise', name: "Cable Lateral Raise", category: 'Shoulders', muscles: ['sideDelts'] },
  { id: 'single-arm-cable-lateral-raise', name: "Single-Arm Cable Lateral Raise", category: 'Shoulders', muscles: ['sideDelts'] },
  { id: 'machine-lateral-raise', name: "Machine Lateral Raise", category: 'Shoulders', muscles: ['sideDelts'] },
  { id: 'lean-away-cable-lateral-raise', name: "Lean-Away Cable Lateral Raise", category: 'Shoulders', muscles: ['sideDelts'] },
  { id: 'dumbbell-front-raise', name: "Dumbbell Front Raise", category: 'Shoulders', muscles: ['frontDelts'] },
  { id: 'cable-front-raise', name: "Cable Front Raise", category: 'Shoulders', muscles: ['frontDelts'] },
  { id: 'plate-front-raise', name: "Plate Front Raise", category: 'Shoulders', muscles: ['frontDelts'] },
  { id: 'barbell-front-raise', name: "Barbell Front Raise", category: 'Shoulders', muscles: ['frontDelts'] },
  { id: 'reverse-dumbbell-fly', name: "Reverse Dumbbell Fly", category: 'Shoulders', muscles: ['rearDelts'] },
  { id: 'reverse-pec-deck', name: "Reverse Pec Deck", category: 'Shoulders', muscles: ['rearDelts'] },
  { id: 'cable-rear-delt-fly', name: "Cable Rear-Delt Fly", category: 'Shoulders', muscles: ['rearDelts'] },
  { id: 'bent-over-dumbbell-rear-delt-raise', name: "Bent-Over Dumbbell Rear-Delt Raise", category: 'Shoulders', muscles: ['rearDelts'] },
  { id: 'cable-upright-row', name: "Cable Upright Row", category: 'Shoulders', muscles: ['sideDelts', 'upperBack'] },
  { id: 'barbell-upright-row', name: "Barbell Upright Row", category: 'Shoulders', muscles: ['sideDelts', 'upperBack'] },
  { id: 'barbell-curl', name: "Barbell Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'ez-bar-curl', name: "EZ-Bar Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'dumbbell-curl', name: "Dumbbell Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'alternating-dumbbell-curl', name: "Alternating Dumbbell Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'hammer-curl', name: "Hammer Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'cross-body-hammer-curl', name: "Cross-Body Hammer Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'incline-dumbbell-curl', name: "Incline Dumbbell Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'preacher-curl', name: "Preacher Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'ez-bar-preacher-curl', name: "EZ-Bar Preacher Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'dumbbell-preacher-curl', name: "Dumbbell Preacher Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'machine-preacher-curl', name: "Machine Preacher Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'cable-curl', name: "Cable Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'straight-bar-cable-curl', name: "Straight-Bar Cable Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'ez-bar-cable-curl', name: "EZ-Bar Cable Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'rope-cable-curl', name: "Rope Cable Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'bayesian-cable-curl', name: "Bayesian Cable Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'spider-curl', name: "Spider Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'concentration-curl', name: "Concentration Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'drag-curl', name: "Drag Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'zottman-curl', name: "Zottman Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'reverse-curl', name: "Reverse Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'cable-hammer-curl', name: "Cable Hammer Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'dumbbell-waiter-curl', name: "Dumbbell Waiter Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'machine-biceps-curl', name: "Machine Biceps Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: '21s-biceps-curl', name: "21s Biceps Curl", category: 'Biceps', muscles: ['biceps'] },
  { id: 'triceps-pushdown', name: "Triceps Pushdown", category: 'Triceps', muscles: ['triceps'] },
  { id: 'rope-triceps-pushdown', name: "Rope Triceps Pushdown", category: 'Triceps', muscles: ['triceps'] },
  { id: 'straight-bar-triceps-pushdown', name: "Straight-Bar Triceps Pushdown", category: 'Triceps', muscles: ['triceps'] },
  { id: 'v-bar-triceps-pushdown', name: "V-Bar Triceps Pushdown", category: 'Triceps', muscles: ['triceps'] },
  { id: 'single-arm-cable-pushdown', name: "Single-Arm Cable Pushdown", category: 'Triceps', muscles: ['triceps'] },
  { id: 'overhead-cable-triceps-extension', name: "Overhead Cable Triceps Extension", category: 'Triceps', muscles: ['triceps'] },
  { id: 'rope-overhead-triceps-extension', name: "Rope Overhead Triceps Extension", category: 'Triceps', muscles: ['triceps'] },
  { id: 'dumbbell-overhead-triceps-extension', name: "Dumbbell Overhead Triceps Extension", category: 'Triceps', muscles: ['triceps'] },
  { id: 'single-arm-dumbbell-overhead-extension', name: "Single-Arm Dumbbell Overhead Extension", category: 'Triceps', muscles: ['triceps'] },
  { id: 'ez-bar-skull-crushers', name: "EZ-Bar Skull Crushers", category: 'Triceps', muscles: ['triceps'] },
  { id: 'barbell-skull-crushers', name: "Barbell Skull Crushers", category: 'Triceps', muscles: ['triceps'] },
  { id: 'dumbbell-skull-crushers', name: "Dumbbell Skull Crushers", category: 'Triceps', muscles: ['triceps'] },
  { id: 'incline-skull-crushers', name: "Incline Skull Crushers", category: 'Triceps', muscles: ['triceps'] },
  { id: 'close-grip-bench-press-2', name: "Close-Grip Bench Press (Triceps)", category: 'Triceps', muscles: ['triceps'] },
  { id: 'jm-press', name: "JM Press", category: 'Triceps', muscles: ['triceps'] },
  { id: 'cable-triceps-extension', name: "Cable Triceps Extension", category: 'Triceps', muscles: ['triceps'] },
  { id: 'cross-body-cable-triceps-extension', name: "Cross-Body Cable Triceps Extension", category: 'Triceps', muscles: ['triceps'] },
  { id: 'machine-triceps-extension', name: "Machine Triceps Extension", category: 'Triceps', muscles: ['triceps'] },
  { id: 'bench-dips', name: "Bench Dips", category: 'Triceps', muscles: ['triceps'] },
  { id: 'parallel-bar-dips', name: "Parallel-Bar Dips", category: 'Triceps', muscles: ['triceps'] },
  { id: 'assisted-dips', name: "Assisted Dips", category: 'Triceps', muscles: ['triceps'] },
  { id: 'weighted-dips', name: "Weighted Dips", category: 'Triceps', muscles: ['triceps'] },
  { id: 'dumbbell-kickback', name: "Dumbbell Kickback", category: 'Triceps', muscles: ['triceps'] },
  { id: 'cable-kickback', name: "Cable Kickback (Triceps)", category: 'Triceps', muscles: ['triceps'] },
  { id: 'bodyweight-triceps-extension', name: "Bodyweight Triceps Extension", category: 'Triceps', muscles: ['triceps'] },
  { id: 'barbell-back-squat', name: "Barbell Back Squat", category: 'Quads', muscles: ['quads'] },
  { id: 'high-bar-squat', name: "High-Bar Squat", category: 'Quads', muscles: ['quads'] },
  { id: 'low-bar-squat', name: "Low-Bar Squat", category: 'Quads', muscles: ['quads'] },
  { id: 'front-squat', name: "Front Squat", category: 'Quads', muscles: ['quads'] },
  { id: 'goblet-squat', name: "Goblet Squat", category: 'Quads', muscles: ['quads'] },
  { id: 'hack-squat', name: "Hack Squat", category: 'Quads', muscles: ['quads'] },
  { id: 'hack-squat-machine', name: "Hack Squat Machine", category: 'Quads', muscles: ['quads'] },
  { id: 'leg-press', name: "Leg Press", category: 'Quads', muscles: ['quads'] },
  { id: 'horizontal-leg-press', name: "Horizontal Leg Press", category: 'Quads', muscles: ['quads'] },
  { id: 'single-leg-leg-press', name: "Single-Leg Leg Press", category: 'Quads', muscles: ['quads'] },
  { id: 'smith-machine-squat', name: "Smith Machine Squat", category: 'Quads', muscles: ['quads'] },
  { id: 'bulgarian-split-squat', name: "Bulgarian Split Squat", category: 'Quads', muscles: ['quads'] },
  { id: 'dumbbell-bulgarian-split-squat', name: "Dumbbell Bulgarian Split Squat", category: 'Quads', muscles: ['quads'] },
  { id: 'reverse-lunge', name: "Reverse Lunge", category: 'Quads', muscles: ['quads'] },
  { id: 'forward-lunge', name: "Forward Lunge", category: 'Quads', muscles: ['quads'] },
  { id: 'walking-lunges', name: "Walking Lunges", category: 'Quads', muscles: ['quads'] },
  { id: 'dumbbell-lunges', name: "Dumbbell Lunges", category: 'Quads', muscles: ['quads'] },
  { id: 'barbell-lunges', name: "Barbell Lunges", category: 'Quads', muscles: ['quads'] },
  { id: 'step-ups', name: "Step-Ups", category: 'Quads', muscles: ['quads'] },
  { id: 'weighted-step-ups', name: "Weighted Step-Ups", category: 'Quads', muscles: ['quads'] },
  { id: 'sissy-squat', name: "Sissy Squat", category: 'Quads', muscles: ['quads'] },
  { id: 'spanish-squat', name: "Spanish Squat", category: 'Quads', muscles: ['quads'] },
  { id: 'belt-squat', name: "Belt Squat", category: 'Quads', muscles: ['quads'] },
  { id: 'pendulum-squat', name: "Pendulum Squat", category: 'Quads', muscles: ['quads'] },
  { id: 'leg-extension', name: "Leg Extension", category: 'Quads', muscles: ['quads'] },
  { id: 'romanian-deadlift', name: "Romanian Deadlift", category: 'Hamstrings & Glutes', muscles: ['hamstrings', 'glutes', 'lowerBack'] },
  { id: 'dumbbell-romanian-deadlift', name: "Dumbbell Romanian Deadlift", category: 'Hamstrings & Glutes', muscles: ['hamstrings', 'glutes', 'lowerBack'] },
  { id: 'single-leg-romanian-deadlift', name: "Single-Leg Romanian Deadlift", category: 'Hamstrings & Glutes', muscles: ['hamstrings', 'glutes', 'lowerBack'] },
  { id: 'stiff-leg-deadlift', name: "Stiff-Leg Deadlift", category: 'Hamstrings & Glutes', muscles: ['hamstrings', 'glutes', 'lowerBack'] },
  { id: 'conventional-deadlift', name: "Conventional Deadlift", category: 'Hamstrings & Glutes', muscles: ['hamstrings', 'glutes', 'lowerBack'] },
  { id: 'sumo-deadlift', name: "Sumo Deadlift", category: 'Hamstrings & Glutes', muscles: ['hamstrings', 'glutes', 'lowerBack'] },
  { id: 'trap-bar-deadlift', name: "Trap-Bar Deadlift", category: 'Hamstrings & Glutes', muscles: ['hamstrings', 'glutes', 'lowerBack'] },
  { id: 'deficit-deadlift', name: "Deficit Deadlift", category: 'Hamstrings & Glutes', muscles: ['hamstrings', 'glutes', 'lowerBack'] },
  { id: 'rack-pull', name: "Rack Pull", category: 'Hamstrings & Glutes', muscles: ['hamstrings', 'glutes', 'lowerBack'] },
  { id: 'good-morning', name: "Good Morning", category: 'Hamstrings & Glutes', muscles: ['hamstrings', 'glutes', 'lowerBack'] },
  { id: 'seated-leg-curl', name: "Seated Leg Curl", category: 'Hamstrings & Glutes', muscles: ['hamstrings'] },
  { id: 'lying-leg-curl', name: "Lying Leg Curl", category: 'Hamstrings & Glutes', muscles: ['hamstrings'] },
  { id: 'standing-leg-curl', name: "Standing Leg Curl", category: 'Hamstrings & Glutes', muscles: ['hamstrings'] },
  { id: 'single-leg-leg-curl', name: "Single-Leg Leg Curl", category: 'Hamstrings & Glutes', muscles: ['hamstrings'] },
  { id: 'nordic-hamstring-curl', name: "Nordic Hamstring Curl", category: 'Hamstrings & Glutes', muscles: ['hamstrings'] },
  { id: 'glute-ham-raise', name: "Glute-Ham Raise", category: 'Hamstrings & Glutes', muscles: ['glutes'] },
  { id: 'barbell-hip-thrust', name: "Barbell Hip Thrust", category: 'Hamstrings & Glutes', muscles: ['glutes'] },
  { id: 'dumbbell-hip-thrust', name: "Dumbbell Hip Thrust", category: 'Hamstrings & Glutes', muscles: ['glutes'] },
  { id: 'smith-machine-hip-thrust', name: "Smith Machine Hip Thrust", category: 'Hamstrings & Glutes', muscles: ['glutes'] },
  { id: 'machine-hip-thrust', name: "Machine Hip Thrust", category: 'Hamstrings & Glutes', muscles: ['glutes'] },
  { id: 'glute-bridge', name: "Glute Bridge", category: 'Hamstrings & Glutes', muscles: ['glutes'] },
  { id: 'single-leg-glute-bridge', name: "Single-Leg Glute Bridge", category: 'Hamstrings & Glutes', muscles: ['glutes'] },
  { id: 'cable-pull-through', name: "Cable Pull-Through", category: 'Hamstrings & Glutes', muscles: ['hamstrings'] },
  { id: 'kettlebell-swing', name: "Kettlebell Swing", category: 'Hamstrings & Glutes', muscles: ['glutes', 'hamstrings'] },
  { id: 'dumbbell-swing', name: "Dumbbell Swing", category: 'Hamstrings & Glutes', muscles: ['glutes', 'hamstrings'] },
  { id: 'cable-kickback-2', name: "Cable Kickback (Glutes)", category: 'Hamstrings & Glutes', muscles: ['glutes'] },
  { id: 'glute-kickback-machine', name: "Glute Kickback Machine", category: 'Hamstrings & Glutes', muscles: ['glutes'] },
  { id: 'cable-glute-kickback', name: "Cable Glute Kickback", category: 'Hamstrings & Glutes', muscles: ['glutes'] },
  { id: 'hip-abduction-machine', name: "Hip Abduction Machine", category: 'Hamstrings & Glutes', muscles: ['glutes'] },
  { id: 'cable-hip-abduction', name: "Cable Hip Abduction", category: 'Hamstrings & Glutes', muscles: ['glutes'] },
  { id: 'standing-calf-raise', name: "Standing Calf Raise", category: 'Calves', muscles: ['calves'] },
  { id: 'seated-calf-raise', name: "Seated Calf Raise", category: 'Calves', muscles: ['calves'] },
  { id: 'leg-press-calf-raise', name: "Leg Press Calf Raise", category: 'Calves', muscles: ['calves'] },
  { id: 'smith-machine-calf-raise', name: "Smith Machine Calf Raise", category: 'Calves', muscles: ['calves'] },
  { id: 'dumbbell-calf-raise', name: "Dumbbell Calf Raise", category: 'Calves', muscles: ['calves'] },
  { id: 'single-leg-calf-raise', name: "Single-Leg Calf Raise", category: 'Calves', muscles: ['calves'] },
  { id: 'donkey-calf-raise', name: "Donkey Calf Raise", category: 'Calves', muscles: ['calves'] },
  { id: 'machine-calf-raise', name: "Machine Calf Raise", category: 'Calves', muscles: ['calves'] },
  { id: 'tibialis-raise', name: "Tibialis Raise", category: 'Calves', muscles: ['calves'] },
  { id: 'seated-tibialis-raise', name: "Seated Tibialis Raise", category: 'Calves', muscles: ['calves'] },
  { id: 'crunches', name: "Crunches", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'weighted-crunches', name: "Weighted Crunches", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'cable-crunches', name: "Cable Crunches", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'machine-crunches', name: "Machine Crunches", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'decline-crunches', name: "Decline Crunches", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'sit-ups', name: "Sit-Ups", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'decline-sit-ups', name: "Decline Sit-Ups", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'hanging-knee-raises', name: "Hanging Knee Raises", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'hanging-leg-raises', name: "Hanging Leg Raises", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'captains-chair-knee-raise', name: "Captain's Chair Knee Raise", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'captains-chair-leg-raise', name: "Captain's Chair Leg Raise", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'lying-leg-raises', name: "Lying Leg Raises", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'reverse-crunches', name: "Reverse Crunches", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'bicycle-crunches', name: "Bicycle Crunches", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'russian-twists', name: "Russian Twists", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'weighted-russian-twists', name: "Weighted Russian Twists", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'ab-wheel-rollout', name: "Ab Wheel Rollout", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'barbell-rollout', name: "Barbell Rollout", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'plank', name: "Plank", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'weighted-plank', name: "Weighted Plank", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'side-plank', name: "Side Plank", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'copenhagen-plank', name: "Copenhagen Plank", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'dead-bug', name: "Dead Bug", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'bird-dog', name: "Bird Dog", category: 'Core & Abs', muscles: ['abs', 'lowerBack'] },
  { id: 'pallof-press', name: "Pallof Press", category: 'Core & Abs', muscles: ['abs'] },
  { id: 'clean', name: "Clean", category: 'Full Body', muscles: ['quads', 'hamstrings', 'upperBack'] },
  { id: 'power-clean', name: "Power Clean", category: 'Full Body', muscles: ['quads', 'hamstrings', 'upperBack'] },
  { id: 'hang-clean', name: "Hang Clean", category: 'Full Body', muscles: ['quads', 'hamstrings', 'upperBack'] },
  { id: 'clean-press', name: "Clean & Press", category: 'Full Body', muscles: ['quads', 'hamstrings', 'upperBack'] },
  { id: 'snatch', name: "Snatch", category: 'Full Body', muscles: ['quads', 'hamstrings', 'upperBack'] },
  { id: 'power-snatch', name: "Power Snatch", category: 'Full Body', muscles: ['quads', 'hamstrings', 'upperBack'] },
  { id: 'push-press', name: "Push Press", category: 'Full Body', muscles: ['quads', 'hamstrings', 'upperBack'] },
  { id: 'thruster', name: "Thruster", category: 'Full Body', muscles: ['quads', 'frontDelts'] },
  { id: 'dumbbell-thruster', name: "Dumbbell Thruster", category: 'Full Body', muscles: ['quads', 'frontDelts'] },
  { id: 'kettlebell-clean', name: "Kettlebell Clean", category: 'Full Body', muscles: ['quads', 'hamstrings', 'upperBack'] },
  { id: 'kettlebell-clean-press', name: "Kettlebell Clean & Press", category: 'Full Body', muscles: ['quads', 'hamstrings', 'upperBack'] },
  { id: 'turkish-get-up', name: "Turkish Get-Up", category: 'Full Body', muscles: ['abs', 'sideDelts'] },
  { id: 'farmers-walk', name: "Farmer's Walk", category: 'Full Body', muscles: ['upperBack', 'abs'] },
  { id: 'suitcase-carry', name: "Suitcase Carry", category: 'Full Body', muscles: ['upperBack', 'abs'] },
  { id: 'waiters-carry', name: "Waiter's Carry", category: 'Full Body', muscles: ['upperBack', 'abs'] },
  { id: 'sled-push', name: "Sled Push", category: 'Conditioning', muscles: ['quads', 'glutes'] },
  { id: 'sled-pull', name: "Sled Pull", category: 'Conditioning', muscles: ['quads', 'glutes'] },
  { id: 'battle-ropes', name: "Battle Ropes", category: 'Conditioning', muscles: ['sideDelts', 'abs'] },
  { id: 'box-jumps', name: "Box Jumps", category: 'Conditioning', muscles: ['quads', 'glutes', 'calves'] },
  { id: 'broad-jumps', name: "Broad Jumps", category: 'Conditioning', muscles: ['quads', 'glutes', 'calves'] },
  { id: 'burpees', name: "Burpees", category: 'Conditioning', muscles: ['chest', 'quads', 'abs'] },
  { id: 'mountain-climbers', name: "Mountain Climbers", category: 'Conditioning', muscles: ['abs'] },
  { id: 'bear-crawl', name: "Bear Crawl", category: 'Conditioning', muscles: ['abs', 'sideDelts'] },
  { id: 'prowler-push', name: "Prowler Push", category: 'Conditioning', muscles: ['quads', 'glutes'] },
  { id: 'assault-bike-sprint', name: "Assault Bike Sprint", category: 'Conditioning', muscles: ['quads', 'calves'] },
]

export function findExercise(id: string): ExerciseDef | undefined {
  return exerciseLibrary.find((e) => e.id === id)
}

export function findExerciseByName(name: string): ExerciseDef | undefined {
  return exerciseLibrary.find((e) => e.name === name)
}
